import pb from '@/lib/pocketbase'

export type FormFieldType =
  | 'text'
  | 'textarea'
  | 'email'
  | 'number'
  | 'select'
  | 'radio'
  | 'checkbox'
  | 'date'
  // Display-only fields — render content between questions, collect no answer.
  | 'section'
  | 'image'

export interface FormField {
  /** Stable id generated when the field is added (e.g. "fld_ab12"). */
  id: string
  label: string
  /** English label — only used when the form has multiLanguage = true. */
  label_en?: string
  type: FormFieldType
  /** Only meaningful for answer fields (text…date); false for display fields. */
  required: boolean
  /** select / radio / checkbox only. */
  options?: string[]
  placeholder?: string
  /** section only: markdown body (Dutch). */
  content?: string
  /** section only: markdown body in English (multiLanguage forms). */
  content_en?: string
  /** image only: URL of the image shown between questions. */
  imageUrl?: string
}

export interface Form {
  id: string
  /** Random URL-safe code — the public form lives at formUrl(code). */
  code: string
  title: string
  description?: string
  multiLanguage: boolean
  active: boolean
  fields: FormField[]
  /** Processing hook key — picked from FORM_HOOKS in the builder. */
  hook?: string
  createdBy?: string
  created?: string
  updated?: string
}

export interface FormSubmission {
  id: string
  form: string
  answers: Record<string, unknown>
  created?: string
  updated?: string
}

// `code` is generated by createForm() (with a uniqueness re-check); the
// server-side hook is the backstop when clients send one themselves.
export type FormCreate = Omit<Form, 'id' | 'code' | 'created' | 'updated'>
export type FormUpdate = Partial<Omit<FormCreate, 'code'>>

/** Public base of the form site. */
export const FORM_SITE_URL = 'https://form.fenrirclub.be'

/** Public URL of a form (its copy-link). */
export function formUrl(code: string): string {
  return `${FORM_SITE_URL}/${code}`
}

// Code alphabet — must match pb_hooks/forms.pb.js (no 0/O/1/l/I).
export const FORM_CODE_ALPHABET = 'abcdefghjkmnpqrstuvwxyz23456789'
export const FORM_CODE_LENGTH = 10

export function generateFormCode(): string {
  let out = ''
  const bytes = new Uint32Array(FORM_CODE_LENGTH)
  crypto.getRandomValues(bytes)
  for (let i = 0; i < FORM_CODE_LENGTH; i++) {
    out += FORM_CODE_ALPHABET[bytes[i] % FORM_CODE_ALPHABET.length]
  }
  return out
}

/**
 * Processing hooks offered in the form builder ("I need this hook for that
 * form"). Keys must match the dispatch branches in pb_hooks/forms.pb.js.
 */
export const FORM_HOOKS: { value: string; label: string; description: string }[] = [
  { value: 'none', label: 'None', description: 'Just collect and store the answers.' },
{
    value: 'bugticket',
    label: 'Bug ticket',
    description: 'Creates a GitHub issue in the Fenrir repo from the answers (needs GITHUB_TOKEN).',
  },
]

export async function getForms(): Promise<Form[]> {
  return pb.collection('forms').getFullList<Form>({
    sort: '-created',
    expand: 'createdBy',
    requestKey: null,
  })
}

export async function createForm(data: FormCreate): Promise<Form> {
  // Generate the code client-side (hook is the backstop); re-check uniqueness.
  let code = generateFormCode()
  for (let attempt = 0; attempt < 5; attempt++) {
    const existing = await pb.collection('forms').getFirstListItem<Form>(
      `code = "${code}"`,
      { requestKey: null },
    ).catch(() => null)
    if (!existing) break
    code = generateFormCode()
  }
  return pb.collection('forms').create<Form>({
    ...data,
    code,
    // Who created it — display only (the plan's `createdBy` field).
    ...(pb.authStore.record?.id ? { createdBy: pb.authStore.record.id } : {}),
  })
}

export async function updateForm(id: string, data: FormUpdate): Promise<Form> {
  return pb.collection('forms').update<Form>(id, data)
}

export async function deleteForm(id: string): Promise<void> {
  // Submissions cascade automatically (relation with cascadeDelete).
  await pb.collection('forms').delete(id)
}

/** Submissions for one form, newest first. */
export async function getFormSubmissions(formId: string): Promise<FormSubmission[]> {
  return pb.collection('form_submissions').getFullList<FormSubmission>({
    filter: `form = "${formId}"`,
    sort: '-created',
    requestKey: null,
  })
}

// ── Image uploads (image fields of a form) ───────────────────────────────────
// Files live in the `form_images` collection (one record per image); the
// resolved file URL is stored in the field's `imageUrl` in the form's fields
// JSON, so the public form site only ever sees a plain URL.

export interface FormImage {
  /** The form_images record id — used to clean up replaced/removed uploads. */
  id: string
  url: string
}

/** Upload a new image for one image field of a form. */
export async function uploadFormImage(formId: string, fieldId: string, file: File): Promise<FormImage> {
  const fd = new FormData()
  fd.append('form', formId)
  fd.append('fieldId', fieldId)
  fd.append('file', file)
  const rec = await pb.collection('form_images').create<Record<string, unknown>>(fd)
  const filename = String(rec.file)
  return {
    id: String(rec.id),
    url: pb.files.getURL(rec, filename),
  }
}

/** Delete a previously uploaded form image (replaced or removed). */
export async function deleteFormImage(recordId: string): Promise<void> {
  await pb.collection('form_images').delete(recordId)
}

/**
 * If an imageUrl points at a form_images upload, return the record id so the
 * old upload can be cleaned up when the image is replaced or removed.
 */
export function formImageRecordId(imageUrl: string): string | null {
  const m = imageUrl.match(/\/api\/files\/form_images\/([a-zA-Z0-9]+)\//)
  return m ? m[1] : null
}


